### ISSUE TITLE
Не работает на CPU

### ISSUE THREAD

**Issue by MichaelMonashev** [ai-forever/Kandinsky-2#25]
Code to reproduce:
```
from kandinsky2 import get_kandinsky2

model = get_kandinsky2('cpu', task_type='text2img', cache_dir='/tmp/kandinsky2', model_version='2.1', use_flash_attention=False)
images = model.generate_text2img("red cat, 4k photo", num_steps=100, batch_size=1, guidance_scale=4, h=256, w=256, sampler='p_sampler', prior_cf_scale=4, prior_steps="5")
```
error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/kandinsky2/kandinsky2_1_model.py", line 315, in generate_text2img
    image_emb = self.generate_clip_emb(
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/michael/.local/lib/python3.8/site-packages/kandinsky2/kandinsky2_1_model.py", line 168, in generate_clip_emb
    img_feat = self.prior(
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/kandinsky2/model/prior.py", line 373, in forward
    sample = sample_fn(
  File "/home/xxx/.local/lib/python3.8/site-packages/kandinsky2/model/gaussian_diffusion.py", line 413, in p_sample_loop
    for sample in self.p_sample_loop_progressive(
  File "/home/xxx/.local/lib/python3.8/site-packages/kandinsky2/model/gaussian_diffusion.py", line 466, in p_sample_loop_progressive
    out = self.p_sample(
  File "/home/xxx/.local/lib/python3.8/site-packages/kandinsky2/model/gaussian_diffusion.py", line 369, in p_sample
    out = self.p_mean_variance(
  File "/home/xxx/.local/lib/python3.8/site-packages/kandinsky2/model/respace.py", line 102, in p_mean_variance
    return super().p_mean_variance(self._wrap_model(model), *args, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/kandinsky2/model/gaussian_diffusion.py", line 251, in p_mean_variance
    model_output = model(x, s_t, **model_kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/kandinsky2/model/respace.py", line 133, in __call__
    return self.model(x, new_ts, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/kandinsky2/model/prior.py", line 354, in guided_model_fn
    model_out = self.model(combined, ts, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/kandinsky2/model/prior.py", line 240, in forward
    t_emb = self.time_embed(
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xxx/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: "addmm_impl_cpu_" not implemented for 'Half'
```

**Comment by eddir** [comment]
For everone having issues with running Kantinsky-2 on CPU here is a [docker configuration](https://github.com/eddir/Kandinsky-docker-cpu) that works for me.

**Comment by hdnh2006** [comment]
> self.use_fp16

Hello, thanks for your contribution, I tried, I changed the code you suggested and It wasn't possible to run into CPU :-(
