### ISSUE TITLE
cant`get file

### ISSUE THREAD

**Issue by mmmmmomo** [ai-forever/Kandinsky-2#56]
when i run 
`model = get_kandinsky2('cuda', task_type='text2img', model_version='2.1', use_flash_attention=False)`

,it raise error
`
Traceback (most recent call last):
  File "sketch2img.py", line 24, in <module>
    model = get_kandinsky2('cuda', task_type='text2img', model_version='2.0', use_flash_attention=False)
  File "/root/jobs/Kandinsky-2/kandinsky2/__init__.py", line 172, in get_kandinsky2
    model = get_kandinsky2_0(
  File "/root/jobs/Kandinsky-2/kandinsky2/__init__.py", line 28, in get_kandinsky2_0
    cached_download(
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/huggingface_hub/utils/_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "/root/miniconda3/envs/test/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 729, in cached_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the cached path. Please try again or make sure your Internet connection is on.`

it seems like the file can not be found,what can i do to resolve it

**Comment by mmmmmomo** [comment]
i got it,it made error when i download files
